# on: push

# jobs:
#     tests-and-grading: 
#         runs-on: ubuntu-latest
#         steps:
#           - name : checkout repo
#             uses: actions/checkout@v4.2.2

#           - name : install dependencies
#             run: |
#                 sudo apt-get update
#                 sudo apt-get install -y 

name: auto-grading

on: [push]

env:
  CARGO_TERM_COLOR: always
  rust_toolchain: nightly

jobs:
  basic-test:
    runs-on: ubuntu-latest
    outputs:
      points: ${{ steps.end.outputs.points}}
    container:
      image: duskmoon/dev-env:rcore-ci
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: |
          qemu-system-riscv64 --version
          rustup target add riscv64gc-unknown-none-elf
          git config --global --add safe.directory /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}
          git clone https://github.com/LearningOS/rCore-Tutorial-Checker-2025S.git ci-user
          git clone https://github.com/LearningOS/rCore-Tutorial-Test-2025S.git ci-user/user
          ID=`git rev-parse --abbrev-ref HEAD | grep -oP 'ch\K[0-9]'`
          # cd ci-user && make test CHAPTER=$ID passwd=${{ secrets.BASE_TEST_TOKEN }}
          cd ci-user && make test CHAPTER=$ID passwd=${{ secrets.BASE_TEST_TOKEN }} > ../output.txt
          cat ../output.txt
      - name: end
        id: end
        run: |
          cat output.txt | grep -a "Test passed" | grep -oP "\d{1,}/\d{1,}" | xargs -i echo "points={}"
          cat output.txt | grep -a "Test passed" | grep -oP "\d{1,}/\d{1,}" | xargs -i echo "points={}" >> $GITHUB_OUTPUT
  deploy:
    if: github.repository != 'arceos-org/oscamp'
    name: Deploy to pages
    needs: basic-test
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        continue-on-error: true
        with:
          ref: 'gh-pages'
      - name: Save Log File
        uses: yfblock/multi-rank-log@main
        with:
          public-dir: classroom
          points: ${{ needs.basic-test.outputs.points }}
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: ./classroom
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: check score
        env:
          course_id: ${{ secrets.RCORE_2025_SPRING_COURSE_ID }}
          post_api: ${{ secrets.RCORE_2025_SPRING_POST_API }}
          token: ${{ secrets.RCORE_2025_SPRING_TOKEN }}
        run: |
          score=$(( $(grep -o 'ch' classroom/latest.json | wc -l) * 100))
          cat classroom/latest.json
          echo $score

          github_user="${{ github.actor }}"

          # 生成 JSON 结果
          score_json=$(jq -n \
            --arg channel "github" \
            --argjson courseId "$course_id" \
            --arg name "$github_user" \
            --argjson score "$score" \
            --argjson totalScore 500 \
            '{channel: $channel, courseId: $courseId, name: $name, score: $score, totalScore: $totalScore}')

            response=$(curl -X POST $post_api \
            -H "accept: application/json;charset=utf-8" \
            -H "Content-Type: application/json" \
            -H "token: $token" \
            -d "$score_json" \
            -v)

            echo "Response: $response"

            if echo "$response" | grep -q '"result":1'; then
            echo "Success: The result field contains 1."
            else
            echo "Error: The result field does not contain 1."
            exit 1
            fi
